# Generated by Django 4.2.7 on 2025-12-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, default='Genérico', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('co2_footprint', models.FloatField(default=0.0, help_text='CO2 en kg')),
                ('sustainability_score', models.IntegerField(default=0, help_text='0-100 Score')),
                ('is_fair_trade', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_optimized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_suggested_alternative', models.BooleanField(default=False)),
                ('substitution_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('original_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shoppinglist')),
            ],
        ),
    ]
